### ISSUE TITLE
I NEED AN IMAGEHOST!

### ISSUE THREAD

**Issue by OleMchls** [OleMchls/atom-wordcount#1]
![atom-wordcount](https://f.cloud.github.com/assets/584259/2331039/66e2bba2-a442-11e3-8d1f-7bd92287a40d.gif)

**Comment by nesQuick** [comment]
AGAIN!
![wc-demo](https://cloud.githubusercontent.com/assets/584259/19187373/62f97ad8-8c8b-11e6-85aa-1282f94f509b.gif)
