### ISSUE TITLE
Word/Char count doesn't display on initially-empty tab until tab switch

### ISSUE THREAD

**Issue by jamesbeldock** [OleMchls/atom-wordcount#102]
Recipe to repro in v3.0.0:

1. Open new tab and save new .md document
2. Type lots of .md content
3. Observe: no word count or character count visible
4. Switch tab to other file
5. Observe word count and character count
6. Switch back to new .md file (click on tab)
7. Observe: the word count and char count are now visible!

**Comment by OleMchls** [comment]
@jamesbeldock thanks for reporting this. IIRC this is a regression, but atoms APIs are constantly changing. If you would want to get your feet wet with `atom-wordcount` I would love to see a PR for this :)

**Comment by MarkPuchalaII** [comment]
Bug also seems to happen with untitled documents.

I can't get word count to show at all until I've saved the file as something.
Puts a real stint in trying to write something like essays in atom.

**Comment by OleMchls** [comment]
This is fixed with the release of 3.3.0
