### ISSUE TITLE
Use with Hugo

### ISSUE THREAD

**Issue by jhabdas** [OleMchls/atom-wordcount#106]
I'd like to be able to use this plug-in for translations of a Hugo website. But the content I'm using has a lot of [Shortcodes](https://gohugo.io/content-management/shortcodes/) like:

    {{< highlight go-html-template >}}
    {{< include "themes/after-dark/layouts/_default/single.html" >}}
    {{< /highlight >}}

Is there a way to configure word-count omissions if these types of things using RegExp?

**Comment by OleMchls** [comment]
@jhabdas Generally I agree with that feature request. However, adding support for each and every markup language would result in very complex code. If you are keen to push this forward I encourage you to take a look at https://github.com/OleMchls/atom-wordcount/issues/99 which is a great approach to this issue.

**Comment by jhabdas** [comment]
> However, adding support for each and every markup language would result in very complex code.

Couldn't agree more, which is why I would advise a generalized approach. This issue was intended to get the conversation kicked off. If #99 addresses both the wordcount issue and this one that'll be great.
