### ISSUE TITLE
Words with umlauts are counted two/three times

### ISSUE THREAD

**Issue by alienmindbender** [OleMchls/atom-wordcount#112]
Hi there,

as the title says:

The german word "Füller" for example is counted two times, while the word "Schlösser" is counted three times...

![image](https://user-images.githubusercontent.com/15013291/52128575-99fb0d80-2635-11e9-9a05-dbab87f153fc.png)

**Comment by eiriarte** [comment]
It also happens with accented characters and letters like ñ or ç. So, the phrase "las clínicas españolas" counts as five words, instead of three.

**Comment by davidlday** [comment]
(Note to self) Need to include all Alphabet Characters from [Unicode Latin Script](https://en.wikipedia.org/wiki/List_of_Unicode_characters#Latin_script)

**Comment by davidlday** [comment]
@eiriarte and @alienmindbender - Would you mind providing some sample text and expected word count for testing? A few sentences would suffice.

**Comment by eiriarte** [comment]
@davidlday - Of course:

> CAPÍTULO PRIMERO
>
> Que trata de la condición y ejercicio del famoso hidalgo D. Quijote de la Mancha
>
> En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lentejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda. El resto della concluían sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mismo, los días de entre semana se honraba con su vellori de lo más fino. Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta años, era de complexión recia, seco de carnes, enjuto de rostro; gran madrugador y amigo de la caza. Quieren decir que tenía el sobrenombre de Quijada o Quesada (que en esto hay alguna diferencia en los autores que deste caso escriben), aunque por conjeturas verosímiles se deja entender que se llama Quijana; pero esto importa poco a nuestro cuento; basta que en la narración dél no se salga un punto de la verdad.

**Expected word count**: 234

> El veloz murciélago hindú comía feliz cardillo y kiwi. La cigüeña tocaba el saxofón detrás del palenque de paja.

**Expected word count**: 19

**Comment by alienmindbender** [comment]
Sorry!
I was on holiday!

At the top of my head I can't think of any meaningful sentence - [google](http://www.diktat-truhe.de/diktate/ein-hundeleben.html) to the rescue:

> Wenn Tina aus dem Fenster schaut, sieht sie im Garten neun Bäume. Auf einem der dünnen Äste sitzt ein Täubchen und macht lustige Geräusche. Ihr Hund sitzt nicht weit entfernt gemütlich neben seinem Häuschen und beäugt das Tier. Sein Interesse verfliegt aber schnell, als mit lautem Getöse ein Flugzeug am Himmel vorbeifliegt. Erschrocken fliegt das Täubchen auf und verschwindet im feuchten Gebüsch. Gestern hat es stark geregnet, dennoch sind am bläulichen Himmel immer noch einige Wolken zu sehen.
> Tina schaut den Tieren gerne bei ihrer täglichen Beschäftigung zu. Einmal hat sie die Katze des Nachbarn beobachtet, wie sie über einige Zäune gesprungen ist. Als Tina ihr nachgerannt ist, hat sie sich aber bei einem Sturz eine Beule zugezogen. Trotzdem beneidet sie die Tiere um ihr unbeschwertes Leben. Denn sie muss noch ihre Hausaufgaben erledigen und dann ihr Zimmer aufräumen. Andererseits kann man das wohl auch ein Hundeleben nennen!

Expected wordcount is 148, but 176 in atom.

**Comment by davidlday** [comment]
My apologies for the delay. Thank you both for providing test cases! I've added and pushed to the "extended-charset" branch if either of you are interested in testing it out before the changes are published.

**Comment by eiriarte** [comment]
It works, thank you! 👌
