### ISSUE TITLE
wordcount mismatch

### ISSUE THREAD

**Issue by jieyuefeng** [OleMchls/atom-wordcount#115]
![image](http://asewqa.nj-dingri.com/6b359fa9a535d5d79beaa9cbecc0d03b.png)

**Comment by OleMchls** [comment]
I don’t understand what’s the expected behavior. A single ‘a’ is just 1 character

**Comment by jieyuefeng** [comment]
What's the meaning of the last number in "(1, **2**)", I found it is the same with the "Character Count" when selection, but mismatch when selection contains a new line.

**Comment by davidlday** [comment]
@jieyuefeng - The "(1,2)" on the left isn't part of this package. It's a feature of Atom. If you hover over it, it should say something like, "1 line, 2 characters selected".
