### ISSUE TITLE
Won't count the greek words

### ISSUE THREAD

**Issue by IonianIronist** [OleMchls/atom-wordcount#117]
I don't know if there is an issue with other alphabets (guess it's an encoding problem), but it doesn't seem to count words written in Greek at all, although it counts the characters.

**Comment by davidlday** [comment]
Could you post some sample text with expected word and character counts?

**Comment by IonianIronist** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/36776432/60580486-e20d9000-9d8d-11e9-9dd3-d0703c777629.png)
expected 5 words , got 0

**Comment by davidlday** [comment]
Greek characters weren't covered originally. I'll see if I can add them.

**Comment by davidlday** [comment]
@IonianIronist - Quick question. Do you mean modern Greek only, or ancient Greek as well? See this SO question for reference: https://stackoverflow.com/questions/2502274/greek-characters-regular-expressions-and-c-sharp

**Comment by IonianIronist** [comment]
Well, I only ever write modern Greek and use Atom for some of my school projects.
Also cant imagine anyone wanting to write ancient Greek in Atom, but sure there will be like that one weird guy. The only difference between the two are the accents as far as I'm aware  witch should be these here

**Comment by davidlday** [comment]
@IonianIronist  - I'm so sorry for the long delay in getting this merged. No excuse. I simply got distracted. Merging the PR now.
