### ISSUE TITLE
Doesn't count non-latin words

### ISSUE THREAD

**Issue by dmavroeidis** [OleMchls/atom-wordcount#124]
If I enter a document in Greek, words are not recognised in that language. The only words recognized as words are the number "1943" and a few words in latin script. Not sure if this is the case for other non-latin scripts as well.
![Screenshot 2020-04-03 at 19 20 14](https://user-images.githubusercontent.com/1138524/78382979-4f31a880-75e0-11ea-97e5-091fc9c7bb43.png)

**Comment by dmavroeidis** [comment]
Checked the version on github and it includes counting Greek words. The current version available on atom doesn't. 
This was committed 9 months ago. Is there a plan for a new release?

**Comment by OleMchls** [comment]
What version do you have installed? What’s on atom.io compared to what’s in the package.json?

All versions should have been published to atom.io

**Comment by dmavroeidis** [comment]
Latest release 3.1 was on May 2019. Which doesn't include the fix.

![Screenshot 2020-04-04 at 10 37 11](https://user-images.githubusercontent.com/1138524/78421449-6912d000-7660-11ea-96b6-f6bb6cffcc8e.png)

**Comment by OleMchls** [comment]
I just cut v3.2.0 please check if this fixes the problem :)

**Comment by dmavroeidis** [comment]
Great! Thanks a lot.
