### ISSUE TITLE
Please add option to use thousands separator

### ISSUE THREAD

**Issue by lucasvieites** [OleMchls/atom-wordcount#131]
Hi there,
my personal use of this package is to count characters in a file, this number is often in the several thousand, which gets hard to read when there are no separators.
Could you please add an option to define a "thousands separator"?

Kind regards,
Lucas

**Comment by OleMchls** [comment]
I love the idea. but instead of adding yet another flip switch, what about we use one off the ends provided by the OS:

```shell
$~ env | grep en_US
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
```

I'd love to see a PR for this

**Comment by lucasvieites** [comment]
I'll try and add that myself. I have never done anything in CoffeeScript before, so it will look sloppy.
