### ISSUE TITLE
Feature request: Option to set a character target instead of a word target

### ISSUE THREAD

**Issue by joshua-smart** [OleMchls/atom-wordcount#134]
It would be very useful to see the progress towards a set number of characters instead of words, such as in the case of university application personal statements (4,000 characters)

**Comment by OleMchls** [comment]
Hey @joshua-smart this sounds like a handy addition to me, this should be combined with the existing option to work towards word goals. E.g. dropdown within the option if the value is words or chars:

![Screenshot 2021-09-21 at 17 06 25](https://user-images.githubusercontent.com/584259/134196738-d968556c-d81e-45c9-832d-dc7753de8e6f.png)

PRs are welcome :)
